#!/bin/bash

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C99B11DEB97541F0
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 23F3D4EA75716059
sudo apt-add-repository https://cli.github.com/packages
sudo sed -i.bck '/cli.github.com/ s/sid/bullseye/' /etc/apt/sources.list
sudo rm /etc/apt/sources.list.bck
